# Generated by Django 5.1.1 on 2024-09-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='./default_profile_qtk8ec', upload_to=''),
        ),
    ]
