# Generated by Django 5.1.1 on 2024-09-19 22:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dpjdwg51y/image/upload/v1726782033/k2wgf56y8stabvctolmu.png', max_length=255, verbose_name='image'),
        ),
    ]
